name: yslahn_bet_pro
description: Aviator + Virtual Foot Analyzer
version: 1.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
